import { useState } from 'react';
import { Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from 'react-native';
import { StatusBar } from 'expo-status-bar';

const C={ink:'#17372D',forest:'#235643',cream:'#F7F3E9',paper:'#FFFDF8',gold:'#E7A83E',coral:'#D96B4A',sage:'#DDE7D7',muted:'#6E7B74',rule:'#DDE2DB'};
type Mode='choose'|'individual'|'business';
export function AccountModePreview({close,openMuroora,shop}:{close:()=>void;openMuroora:()=>void;shop:()=>void}){
 const [mode,setMode]=useState<Mode>('choose');
 if(mode==='choose')return <Shell title="Sign in to Musuwo" back={close}><Text style={s.eyebrow}>CHOOSE HOW YOU ARE USING MUSUWO</Text><Text style={s.title}>One identity, two clear spaces.</Text><Text style={s.body}>Your account can have an individual profile, a business profile, or both. Choose the space you need now.</Text><ModeCard icon="○" title="Individual account" text="Shop, enquire, manage personal orders and contact businesses." action="Continue as an individual" onPress={()=>setMode('individual')}/><ModeCard icon="▦" title="Business account" text="Manage your business profile, store, listings, orders and staff." action="Continue as a business" onPress={()=>setMode('business')}/><Text style={s.note}>Preview only · production uses one Musuwo login and server-verified profile access.</Text></Shell>;
 if(mode==='individual')return <Shell title="Musuwo Individual Account" back={()=>setMode('choose')}><View style={s.profile}><View style={s.avatar}><Text style={s.avatarText}>○</Text></View><View><Text style={s.profileTitle}>Individual profile</Text><Text style={s.meta}>Personal shopping and enquiries</Text></View></View><Text style={s.section}>YOUR MUSUWO</Text><Action title="Discover businesses" text="Shopping, food, accommodation and services" onPress={shop}/><Action title="My orders" text="Purchases made through Musuwo"/><Action title="Chats and enquiries" text="Private conversations and contact requests"/><Action title="Saved places and favourites" text="Personal—not visible to business workspaces"/><View style={s.notice}><Text style={s.noticeTitle}>Buying is personal</Text><Text style={s.noticeText}>Switch to your Individual Account before purchasing. A business workspace cannot place personal orders using merchant authority.</Text></View></Shell>;
 return <Shell title="Musuwo Business Account" back={()=>setMode('choose')}><View style={s.profile}><View style={[s.avatar,{backgroundColor:C.gold}]}><Text style={s.avatarText}>B</Text></View><View style={s.grow}><Text style={s.profileTitle}>Business profile</Text><Text style={s.meta}>Authorized stores and operations</Text></View><Text style={s.preview}>PREVIEW</Text></View><View style={s.businessHero}><Text style={s.businessKicker}>YOUR BUSINESS</Text><Text style={s.businessName}>Muroora Mart</Text><Text style={s.businessMeta}>MUR-BIZ-0001 · Founding Merchant</Text><View style={s.scoreRow}><Text style={s.score}>4.5</Text><View><Text style={s.scoreTitle}>Musuwo Business Score</Text><Text style={s.scoreMeta}>Launch assessment · no customer reviews yet</Text></View></View><Pressable style={s.openStore} onPress={openMuroora}><Text style={s.openStoreText}>Open Muroora Mart →</Text></Pressable></View><Text style={s.section}>STORE MANAGEMENT</Text><Action title="Store overview" text="What needs attention right now"/><Action title="Products and listings" text="Photos, prices and availability"/><Action title="Orders" text="Prepare and fulfil Muroora Mart orders"/><Action title="Stock" text="Available, reserved, low and damaged"/><Action title="Staff" text="Muroora-scoped operational access"/><Action title="Business profile" text="Logo, description, hours and fulfilment"/><View style={s.notice}><Text style={s.noticeTitle}>Delivery through Musuwo</Text><Text style={s.noticeText}>Muroora Mart prepares the order. Musuwo coordinates the delivery experience. The independent public Musuwo rider network remains Coming Soon.</Text></View></Shell>;
}
function Shell({title,back,children}:{title:string;back:()=>void;children:React.ReactNode}){return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.phone}><View style={s.header}><Pressable onPress={back} style={s.back}><Text style={s.backText}>‹</Text></Pressable><Text style={s.headerTitle}>{title}</Text><View style={s.back}/></View><ScrollView contentContainerStyle={s.content}>{children}</ScrollView></View></SafeAreaView>}
function ModeCard({icon,title,text,action,onPress}:{icon:string;title:string;text:string;action:string;onPress:()=>void}){return <Pressable style={s.modeCard} onPress={onPress}><View style={s.modeIcon}><Text style={s.modeIconText}>{icon}</Text></View><Text style={s.modeTitle}>{title}</Text><Text style={s.modeText}>{text}</Text><Text style={s.modeAction}>{action} →</Text></Pressable>}
function Action({title,text,onPress}:{title:string;text:string;onPress?:()=>void}){return <Pressable style={s.action} onPress={onPress}><View style={s.grow}><Text style={s.actionTitle}>{title}</Text><Text style={s.meta}>{text}</Text></View><Text style={s.arrow}>›</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.paper},phone:{flex:1,width:'100%',maxWidth:440,alignSelf:'center',backgroundColor:C.paper},header:{height:68,paddingHorizontal:16,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:C.rule},back:{width:42,height:42,borderRadius:21,backgroundColor:C.cream,alignItems:'center',justifyContent:'center'},backText:{fontSize:32,color:C.ink,marginTop:-4},headerTitle:{flex:1,textAlign:'center',fontSize:15,fontWeight:'900',color:C.ink},content:{padding:20,paddingBottom:50},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.4,color:C.coral,marginTop:12},title:{fontSize:32,lineHeight:36,fontWeight:'900',color:C.ink,marginTop:6},body:{fontSize:13,lineHeight:20,color:C.muted,marginTop:12,marginBottom:8},modeCard:{padding:22,borderRadius:24,backgroundColor:C.cream,marginTop:16},modeIcon:{width:48,height:48,borderRadius:16,backgroundColor:C.forest,alignItems:'center',justifyContent:'center'},modeIconText:{fontSize:23,fontWeight:'900',color:'#fff'},modeTitle:{fontSize:20,fontWeight:'900',color:C.ink,marginTop:16},modeText:{fontSize:11,lineHeight:17,color:C.muted,marginTop:5},modeAction:{fontSize:11,fontWeight:'900',color:C.coral,marginTop:18},note:{fontSize:9,lineHeight:15,color:C.muted,textAlign:'center',marginTop:20},profile:{padding:17,borderRadius:22,backgroundColor:C.cream,flexDirection:'row',alignItems:'center',gap:12},avatar:{width:50,height:50,borderRadius:17,backgroundColor:C.forest,alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontWeight:'900',fontSize:18},profileTitle:{fontSize:16,fontWeight:'900',color:C.ink},meta:{fontSize:10,lineHeight:15,color:C.muted,marginTop:3},grow:{flex:1},preview:{fontSize:8,fontWeight:'900',color:C.coral},section:{fontSize:9,fontWeight:'900',letterSpacing:1.3,color:C.muted,marginTop:26,marginBottom:5},action:{minHeight:70,borderBottomWidth:1,borderBottomColor:C.rule,flexDirection:'row',alignItems:'center'},actionTitle:{fontSize:13,fontWeight:'900',color:C.ink},arrow:{fontSize:26,color:C.muted},notice:{padding:16,borderRadius:18,backgroundColor:'#F5E6C9',marginTop:20},noticeTitle:{fontSize:12,fontWeight:'900',color:C.ink},noticeText:{fontSize:10,lineHeight:16,color:C.muted,marginTop:4},businessHero:{padding:22,borderRadius:25,backgroundColor:C.forest,marginTop:16},businessKicker:{fontSize:8,fontWeight:'900',letterSpacing:1.3,color:C.gold},businessName:{fontSize:28,fontWeight:'900',color:'#fff',marginTop:5},businessMeta:{fontSize:10,color:'rgba(255,255,255,.65)',marginTop:4},scoreRow:{flexDirection:'row',alignItems:'center',gap:13,marginTop:20},score:{fontSize:36,fontWeight:'900',color:C.gold},scoreTitle:{fontSize:12,fontWeight:'900',color:'#fff'},scoreMeta:{fontSize:9,color:'rgba(255,255,255,.65)',marginTop:2},openStore:{height:48,borderRadius:24,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',marginTop:20},openStoreText:{fontSize:12,fontWeight:'900',color:C.forest}});
