import { useState, type ReactNode } from 'react';
import { Alert, Linking, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';

const C={ink:'#17372D',forest:'#235643',cream:'#F7F3E9',paper:'#FFFDF8',gold:'#E7A83E',coral:'#D96B4A',sage:'#DDE7D7',muted:'#6E7B74'};
type Route='welcome'|'apply'|'documents'|'review'|'dashboard'|'offer'|'pickup'|'dropoff'|'proof'|'complete'|'earnings'|'history'|'profile'|'issue';
type Tab='Home'|'Deliveries'|'Earnings'|'Profile';

export function RiderFlow({close}:{close:()=>void}){
  const [route,setRoute]=useState<Route>('welcome');
  const [online,setOnline]=useState(false);
  const [tab,setTab]=useState<Tab>('Home');
  const [proof,setProof]=useState<'OTP'|'Photo'>('OTP');
  const [accepted,setAccepted]=useState(false);
  const [issueFrom,setIssueFrom]=useState<'pickup'|'dropoff'>('pickup');
  const [issueCategory,setIssueCategory]=useState('Customer unreachable');
  const [issueSent,setIssueSent]=useState(false);
  const openIssue=(from:'pickup'|'dropoff')=>{setIssueFrom(from);setIssueSent(false);setRoute('issue')};
  const goTab=(next:Tab)=>{setTab(next);setRoute(next==='Home'?'dashboard':next==='Deliveries'?'history':next==='Earnings'?'earnings':'profile')};
  const back=()=>{
    const previous:Partial<Record<Route,Route>>={apply:'welcome',documents:'apply',review:'documents',offer:'dashboard',pickup:'offer',dropoff:'pickup',proof:'dropoff',complete:'dashboard',earnings:'dashboard',history:'dashboard',profile:'dashboard'};
    const next=previous[route]; if(next)setRoute(next); else close();
  };

  if(route==='welcome')return <Frame title="Muroora Delivery" back={close}>
    <View style={s.welcomeHero}><Text style={s.heroEmoji}>🛵</Text><Text style={s.welcomeKicker}>DELIVER WITH PURPOSE</Text><Text style={s.welcomeTitle}>Move essentials.{`\n`}Earn per delivery.</Text><Text style={s.welcomeText}>A mobile-first rider experience built for clear jobs, accountable handovers and transparent earnings.</Text></View>
    <View style={s.benefits}><Benefit icon="◈" title="See earnings first" text="Know the delivery pay before accepting."/><Benefit icon="✓" title="Verified network" text="Every rider follows the same safe process."/><Benefit icon="▤" title="Clear history" text="Track completed jobs and every credit."/></View>
    <Pressable style={s.primary} onPress={()=>setRoute('apply')}><Text style={s.primaryText}>Apply to deliver</Text></Pressable><Pressable style={s.secondary} onPress={()=>setRoute('dashboard')}><Text style={s.secondaryText}>Preview approved rider demo</Text></Pressable>
  </Frame>;

  if(route==='apply')return <Frame title="Rider application" back={back} step="Step 1 of 2">
    <Title kicker="PERSONAL & VEHICLE" title="Tell us about yourself" text="Your private information is only for verification and operations."/>
    <Field label="Display name" value="" placeholder="Your name"/><Field label="Operational phone" value="" placeholder="+263 77 000 0000"/><Field label="Operating area" value="" placeholder="Which suburbs you cover"/>
    <Text style={s.sectionLabel}>VEHICLE</Text><Choice values={['Motorcycle','Bicycle','Car']} selected="Motorcycle"/><Field label="Make and model" value="" placeholder="e.g. Honda CB125"/><Field label="Registration" value="" placeholder="Your plate number"/>
    <Pressable style={s.primary} onPress={()=>setRoute('documents')}><Text style={s.primaryText}>Continue to documents</Text></Pressable>
  </Frame>;

  if(route==='documents')return <Frame title="Verification" back={back} step="Step 2 of 2">
    <Title kicker="SAFE ONBOARDING" title="Complete your rider profile" text="Sensitive legal-document collection is disabled while the verification process is under legal review."/>
    {['Profile photograph','Vehicle photograph','Safety acknowledgement','Rider agreement'].map((x,i)=><Pressable key={x} onPress={()=>Alert.alert(x,i<2?'This demo item is complete.':'The review screen will be connected before onboarding opens.')} style={s.document}><View style={s.docIcon}><Text>{i<2?'✓':'+'}</Text></View><View style={s.grow}><Text style={s.rowTitle}>{x}</Text><Text style={s.rowSub}>{i<2?'Demo item completed':'Tap to review'}</Text></View><Text style={s.chevron}>›</Text></Pressable>)}
    <View style={s.notice}><Text style={s.noticeTitle}>Sensitive verification is currently off</Text><Text style={s.noticeText}>National ID, police clearance and similar documents are not requested in this test build.</Text></View>
    <Pressable style={s.primary} onPress={()=>setRoute('review')}><Text style={s.primaryText}>Submit demo application</Text></Pressable>
  </Frame>;

  if(route==='review')return <Frame title="Application status" back={back}>
    <View style={s.center}><View style={s.reviewIcon}><Text style={s.bigIcon}>◷</Text></View><Text style={s.centerTitle}>Under review</Text><Text style={s.centerText}>The Muroora team checks the operational profile, vehicle details and safety acknowledgement before a rider can go online.</Text><Text style={s.status}>UNDER REVIEW</Text></View>
    <Progress label="Application submitted" done/><Progress label="Operational profile review" active/><Progress label="Safety onboarding"/><Progress label="Approved to deliver" last/>
    <Pressable style={s.primary} onPress={()=>setRoute('dashboard')}><Text style={s.primaryText}>Preview approved dashboard</Text></Pressable>
  </Frame>;

  if(route==='dashboard')return <RiderShell tab={tab} goTab={goTab} close={close}>
    <View style={s.dashHead}><View><Text style={s.kicker}>RIDER PROTOTYPE</Text><Text style={s.dashTitle}>Delivery app</Text></View><View style={s.verified}><Text style={s.verifiedText}>NOT LIVE</Text></View></View>
    <View style={[s.onlineCard,online&&s.onlineCardOn]}><View><Text style={[s.onlineLabel,online&&s.onlineLabelOn]}>{online?'YOU ARE ONLINE':'YOU ARE OFFLINE'}</Text><Text style={[s.onlineTitle,online&&s.onlineTitleOn]}>{online?'Ready for a delivery':'Go online when ready'}</Text><Text style={[s.onlineText,online&&s.onlineTextOn]}>{online?'Your location is used at low frequency while available.':'You will not receive offers while offline.'}</Text></View><Pressable style={[s.switch,online&&s.switchOn]} onPress={()=>setOnline(!online)}><View style={[s.knob,online&&s.knobOn]}/></Pressable></View>
    {online?<Pressable style={s.offerPeek} onPress={()=>setRoute('offer')}><View style={s.pulse}/><View style={s.grow}><Text style={s.offerPeekTitle}>New delivery available</Text><Text style={s.offerPeekText}>Muroora Mart → Dangamvura · $3.80</Text></View><Text style={s.chevron}>›</Text></Pressable>:<View style={s.waiting}><Text style={s.waitingEmoji}>🏠</Text><Text style={s.waitingTitle}>Your time is yours</Text><Text style={s.waitingText}>Go online when you are available for one delivery at a time.</Text></View>}
    <Text style={s.sectionLabel}>TODAY</Text><View style={s.metrics}><Metric value="3" label="Deliveries"/><Metric value="$11.40" label="Earnings"/><Metric value="4.9" label="Rating"/></View>
    <Pressable style={s.tip} onPress={()=>Alert.alert('Safety first','Stop in a safe place before touching the app. Use a phone mount only for passive navigation.') }><Text style={s.tipIcon}>⚠</Text><View style={s.grow}><Text style={s.rowTitle}>Safety first</Text><Text style={s.rowSub}>Never interact with the app while riding.</Text></View></Pressable>
  </RiderShell>;

  if(route==='offer')return <Frame title="Delivery offer" back={back}>
    <View style={s.timer}><Text style={s.timerText}>Offer reserved for demo</Text></View><View style={s.earnHero}><Text style={s.earnLabel}>YOU WILL EARN</Text><Text style={s.earnValue}>$3.80</Text><Text style={s.earnSub}>Posted after successful delivery</Text></View>
    <View style={s.routeCard}><RoutePoint icon="M" title="Pickup" text="Muroora Mart · Mutare Central"/><View style={s.routeLine}/><RoutePoint icon="●" title="Destination area" text="Dangamvura · exact address after acceptance"/></View>
    <View style={s.offerFacts}><Fact value="6.4 km" label="Estimated distance"/><Fact value="25 min" label="Estimated time"/><Fact value="Medium" label="Order size"/></View>
    <View style={s.notice}><Text style={s.noticeTitle}>No cash collection</Text><Text style={s.noticeText}>Order is marked paid. Keep goods upright and protected from heat.</Text></View>
    <View style={s.actions}><Pressable style={s.decline} onPress={()=>setRoute('dashboard')}><Text style={s.declineText}>Decline</Text></Pressable><Pressable style={s.accept} onPress={()=>{setAccepted(true);setRoute('pickup')}}><Text style={s.primaryText}>Accept delivery</Text></Pressable></View>
  </Frame>;

  if(route==='pickup')return <Frame title="Collect order" back={back}>
    <Stage current="PICKUP" title="Head to Muroora Mart" text="Samora Machel Road, Mutare Central" icon="M"/><View style={s.map}><Text style={s.mapText}>YOU  · · · · · ·  MUROORA MART</Text><View style={s.mapMarker}><Text>🛵</Text></View></View>
    <View style={s.code}><Text style={s.codeLabel}>PICKUP REFERENCE</Text><Text style={s.codeValue}>MM-000124</Text></View>
    <Check text="Check order seal and item count"/><Check text="Confirm any special handling notes"/>
    <View style={s.notice}><Text style={s.noticeTitle}>Two-person custody check</Text><Text style={s.noticeText}>Shop staff starts the handover after checking the package. Tap below to confirm that you personally received it.</Text></View>
    <Pressable style={s.primary} onPress={()=>setRoute('dropoff')}><Text style={s.primaryText}>Confirm collection</Text></Pressable><Pressable style={s.secondary} onPress={()=>openIssue('pickup')}><Text style={s.secondaryText}>Report a pickup problem</Text></Pressable>
  </Frame>;

  if(route==='dropoff')return <Frame title="Deliver order" back={back}>
    <Stage current="DROPOFF" title="Deliver to the recipient" text="The address appears here on a real job" icon="●"/><View style={s.map}><Text style={s.mapText}>MUROORA MART  · · · · · ·  RECIPIENT</Text><View style={[s.mapMarker,{left:'68%'}]}><Text>🛵</Text></View></View>
    <View style={s.contact}><View style={s.avatar}><Text style={s.avatarText}>M</Text></View><View style={s.grow}><Text style={s.rowTitle}>Mom</Text><Text style={s.rowSub}>Recipient · phone shown after acceptance</Text></View><Pressable accessibilityLabel="Call recipient" onPress={()=>void Linking.openURL('tel:+263771234567')} style={s.call}><Text style={s.callText}>☎</Text></Pressable></View>
    <View style={s.notice}><Text style={s.noticeTitle}>Delivery note</Text><Text style={s.noticeText}>Call when outside the gate. Do not leave the order unattended.</Text></View>
    <Pressable style={s.primary} onPress={()=>setRoute('proof')}><Text style={s.primaryText}>I have arrived</Text></Pressable><Pressable style={s.secondary} onPress={()=>openIssue('dropoff')}><Text style={s.secondaryText}>Report a delivery problem</Text></Pressable>
  </Frame>;

  if(route==='issue')return <Frame title="Report an issue" back={()=>setRoute(issueFrom)}>
    <Title kicker="FAIR INCIDENT RECORD" title="What happened?" text="Reporting an issue creates a timestamped record for review. It does not automatically blame or suspend anyone."/>
    <Text style={s.sectionLabel}>CATEGORY</Text>
    <Choice values={['Customer unreachable','Incorrect address','Recipient unavailable','Vehicle breakdown','Damaged package','Safety concern','Shop issue','Other']} selected={issueCategory}/>
    <Field label="What should the team know?" value=""/>
    {issueSent&&<View style={s.notice}><Text style={s.noticeTitle}>Demo issue recorded</Text><Text style={s.noticeText}>The production flow sends this to the protected incident ledger for management review.</Text></View>}
    <Pressable style={s.primary} onPress={()=>{setIssueCategory(issueCategory);setIssueSent(true)}}><Text style={s.primaryText}>Submit issue</Text></Pressable>
    <Pressable style={s.secondary} onPress={()=>setRoute(issueFrom)}><Text style={s.secondaryText}>Return to delivery</Text></Pressable>
  </Frame>;

  if(route==='proof')return <Frame title="Proof of delivery" back={back}>
    <Title kicker="FINAL HANDOVER" title="Confirm safe delivery" text="Complete the configured proof before closing the job."/><View style={s.proofTabs}>{(['OTP','Photo'] as const).map(x=><Pressable key={x} style={[s.proofTab,proof===x&&s.proofTabOn]} onPress={()=>setProof(x)}><Text style={[s.proofTabText,proof===x&&s.proofTabTextOn]}>{x}</Text></Pressable>)}</View>
    {proof==='OTP'?<View style={s.otp}><Text style={s.otpTitle}>Enter recipient OTP</Text><Text style={s.otpText}>Ask the recipient for the 6-digit code sent to their phone. The real code is never embedded in this app.</Text><View style={s.otpBoxes}>{Array.from({length:6},(_,i)=><TextInput key={i} style={s.otpBox} maxLength={1} keyboardType="number-pad"/>)}</View></View>:<Pressable style={s.photo} onPress={()=>Alert.alert('Camera unavailable','Photo proof is a visual prototype and does not access your camera yet.')}><Text style={s.photoIcon}>+</Text><Text style={s.photoTitle}>Add delivery photo</Text><Text style={s.photoText}>Demo only—camera access is disabled.</Text></Pressable>}
    <Check text="Recipient has received the complete order"/><Check text="No cash or goods remain to reconcile"/>
    <Pressable style={s.primary} onPress={()=>setRoute('complete')}><Text style={s.primaryText}>Complete delivery</Text></Pressable>
  </Frame>;

  if(route==='complete')return <Frame title="Delivery complete" back={()=>setRoute('dashboard')}>
    <View style={s.center}><View style={s.success}><Text style={s.successText}>✓</Text></View><Text style={s.centerTitle}>Well delivered.</Text><Text style={s.centerText}>Proof was recorded and the recipient’s order is complete.</Text></View><View style={s.credit}><Text style={s.creditLabel}>EARNING CREDITED</Text><Text style={s.creditValue}>+$3.80</Text><Text style={s.creditText}>Delivery MM-000124 · demo ledger entry</Text></View>
    <Pressable style={s.primary} onPress={()=>setRoute('earnings')}><Text style={s.primaryText}>View earnings</Text></Pressable><Pressable style={s.secondary} onPress={()=>setRoute('dashboard')}><Text style={s.secondaryText}>Return to dashboard</Text></Pressable>
  </Frame>;

  if(route==='earnings')return <RiderShell tab="Earnings" goTab={goTab} close={close}><Title kicker="YOUR MONEY" title="Earnings" text="Every completed delivery creates one transparent credit."/><View style={s.balance}><Text style={s.balanceLabel}>AVAILABLE BALANCE</Text><Text style={s.balanceValue}>$24.60</Text><Pressable style={s.payout} onPress={()=>Alert.alert('Payouts not live','Management has not selected a payout provider. No money will move in this beta.')}><Text style={s.payoutText}>Request payout</Text></Pressable></View><View style={s.metrics}><Metric value="$11.40" label="Today"/><Metric value="$42.80" label="This week"/><Metric value="12" label="Deliveries"/></View><Text style={s.sectionLabel}>RECENT ACTIVITY</Text>{[['+$3.80','MM-000124 · Today'],['+$4.20','MM-000119 · Today'],['−$18.00','Payout · Yesterday']].map(([a,b])=><View key={b} style={s.moneyRow}><View><Text style={s.rowTitle}>{b}</Text><Text style={s.rowSub}>{a.startsWith('+')?'Delivery earning':'EcoCash payout'}</Text></View><Text style={[s.money,a.startsWith('−')&&{color:C.muted}]}>{a}</Text></View>)}</RiderShell>;

  if(route==='history')return <RiderShell tab="Deliveries" goTab={goTab} close={close}><Title kicker="DELIVERY RECORD" title="Your deliveries" text="Completed and active work in one place."/>{[['MM-000124','Completed · Dangamvura · $3.80'],['MM-000119','Completed · Chikanga · $4.20'],['MM-000115','Completed · Mutare Central · $3.40']].map(([a,b],i)=><Pressable key={a} style={s.deliveryRow} onPress={()=>i===0&&setRoute('proof')}><View style={s.deliveryCheck}><Text>✓</Text></View><View style={s.grow}><Text style={s.rowTitle}>{a}</Text><Text style={s.rowSub}>{b}</Text></View><Text style={s.chevron}>›</Text></Pressable>)}</RiderShell>;

  return <RiderShell tab="Profile" goTab={goTab} close={close}><Title kicker="RIDER PROTOTYPE" title="Rider profile" text="Your operational and vehicle details will appear here once rider accounts are switched on."/><View style={s.profile}><View style={s.profileAvatar}><Text style={s.profileAvatarText}>·</Text></View><View><Text style={s.rowTitle}>No rider account yet</Text><Text style={s.rowSub}>Rider sign-up is not open</Text></View></View>{['Personal information','Vehicle details','Verification status','Payout method','Safety and support'].map(x=><Pressable key={x} onPress={()=>Alert.alert(x,'This detail screen is represented in the prototype and will use your protected rider profile when connected.')} style={s.deliveryRow}><Text style={s.rowTitle}>{x}</Text><Text style={s.chevron}>›</Text></Pressable>)}<View style={s.notice}><Text style={s.noticeTitle}>{accepted?'Active delivery demo completed':'Operational profile valid'}</Text><Text style={s.noticeText}>Sensitive legal-document verification is disabled in this test build.</Text></View></RiderShell>;
}

function Frame({title,back,children,step}:{title:string;back:()=>void;children:ReactNode;step?:string}){return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.phone}><View style={s.header}><Pressable style={s.back} onPress={back}><Text style={s.backText}>‹</Text></Pressable><View style={s.headCenter}><Text style={s.headTitle}>{title}</Text>{step&&<Text style={s.headStep}>{step}</Text>}</View><View style={s.back}/></View><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>{children}</ScrollView></View></SafeAreaView>}
function RiderShell({tab,goTab,close,children}:{tab:Tab;goTab:(x:Tab)=>void;close:()=>void;children:ReactNode}){return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.phone}><ScrollView contentContainerStyle={s.shellContent} showsVerticalScrollIndicator={false}>{children}<Pressable style={s.exit} onPress={close}><Text style={s.exitText}>Exit rider demo</Text></Pressable></ScrollView><View style={s.tabs}>{(['Home','Deliveries','Earnings','Profile'] as Tab[]).map((x,i)=><Pressable key={x} style={s.tab} onPress={()=>goTab(x)}><Text style={[s.tabIcon,tab===x&&s.tabOn]}>{['⌂','▤','$','○'][i]}</Text><Text style={[s.tabText,tab===x&&s.tabTextOn]}>{x}</Text></Pressable>)}</View></View></SafeAreaView>}
function Title({kicker,title,text}:{kicker:string;title:string;text:string}){return <View style={s.titleBlock}><Text style={s.kicker}>{kicker}</Text><Text style={s.title}>{title}</Text><Text style={s.subtitle}>{text}</Text></View>}
function Field({label,value,placeholder}:{label:string;value:string;placeholder?:string}){return <View style={s.field}><Text style={s.fieldLabel}>{label}</Text><TextInput style={s.fieldInput} defaultValue={value} placeholder={placeholder} placeholderTextColor="#89958F"/></View>}
function Choice({values,selected}:{values:string[];selected:string}){const [choice,setChoice]=useState(selected);return <View style={s.choices}>{values.map(x=><Pressable key={x} style={[s.choice,choice===x&&s.choiceOn]} onPress={()=>setChoice(x)}><View style={[s.radio,choice===x&&s.radioOn]}/><Text style={[s.choiceText,choice===x&&s.choiceTextOn]}>{x}</Text></Pressable>)}</View>}
function Benefit({icon,title,text}:{icon:string;title:string;text:string}){return <View style={s.benefit}><View style={s.benefitIcon}><Text>{icon}</Text></View><View style={s.grow}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowSub}>{text}</Text></View></View>}
function Progress({label,done,active,last}:{label:string;done?:boolean;active?:boolean;last?:boolean}){return <View style={s.progress}><View style={s.progressCol}><View style={[s.progressDot,(done||active)&&s.progressDotOn]}>{done&&<Text style={s.dotCheck}>✓</Text>}</View>{!last&&<View style={[s.progressLine,done&&s.progressLineOn]}/>}</View><Text style={[s.progressLabel,active&&{color:C.coral}]}>{label}</Text></View>}
function Metric({value,label}:{value:string;label:string}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
function RoutePoint({icon,title,text}:{icon:string;title:string;text:string}){return <View style={s.routePoint}><View style={s.routeIcon}><Text style={s.routeIconText}>{icon}</Text></View><View><Text style={s.rowSub}>{title}</Text><Text style={s.rowTitle}>{text}</Text></View></View>}
function Fact({value,label}:{value:string;label:string}){return <View style={s.fact}><Text style={s.factValue}>{value}</Text><Text style={s.factLabel}>{label}</Text></View>}
function Stage({current,title,text,icon}:{current:string;title:string;text:string;icon:string}){return <View style={s.stage}><View style={s.stageIcon}><Text style={s.stageIconText}>{icon}</Text></View><View style={s.grow}><Text style={s.kicker}>{current}</Text><Text style={s.stageTitle}>{title}</Text><Text style={s.rowSub}>{text}</Text></View></View>}
function Check({text}:{text:string}){const [on,setOn]=useState(false);return <Pressable style={s.checkRow} onPress={()=>setOn(!on)}><View style={[s.checkbox,on&&s.checkboxOn]}>{on&&<Text style={s.dotCheck}>✓</Text>}</View><Text style={s.checkText}>{text}</Text></Pressable>}

const s=StyleSheet.create({
 safe:{flex:1,backgroundColor:Platform.OS==='web'?'#E9E6DE':C.paper},phone:{flex:1,width:'100%',maxWidth:440,alignSelf:'center',backgroundColor:C.paper,...Platform.select({web:{boxShadow:'0 0 50px rgba(23,55,45,.12)'}})},header:{height:68,paddingHorizontal:16,flexDirection:'row',alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#DDE2DB'},back:{width:42,height:42,borderRadius:21,backgroundColor:C.cream,alignItems:'center',justifyContent:'center'},backText:{fontSize:32,color:C.ink,marginTop:-4},headCenter:{flex:1,alignItems:'center'},headTitle:{fontSize:16,fontWeight:'800',color:C.ink},headStep:{fontSize:9,color:C.muted,marginTop:2},content:{padding:20,paddingBottom:55},shellContent:{padding:22,paddingTop:32,paddingBottom:120},
 welcomeHero:{backgroundColor:C.forest,borderRadius:28,padding:25,minHeight:340,justifyContent:'flex-end'},heroEmoji:{fontSize:58,marginBottom:32},welcomeKicker:{fontSize:9,fontWeight:'800',letterSpacing:1.5,color:C.gold},welcomeTitle:{fontSize:34,lineHeight:38,fontWeight:'900',color:'#fff',letterSpacing:-1},welcomeText:{fontSize:13,lineHeight:20,color:'rgba(255,255,255,.75)',marginTop:12},benefits:{marginTop:20},benefit:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:11},benefitIcon:{width:42,height:42,borderRadius:14,backgroundColor:C.cream,alignItems:'center',justifyContent:'center'},grow:{flex:1},rowTitle:{fontSize:13,fontWeight:'800',color:C.ink},rowSub:{fontSize:11,lineHeight:16,color:C.muted,marginTop:3},primary:{height:54,borderRadius:27,backgroundColor:C.forest,alignItems:'center',justifyContent:'center',marginTop:20},primaryText:{fontSize:14,fontWeight:'800',color:'#fff'},secondary:{height:52,borderRadius:26,borderWidth:1,borderColor:'#BCC7BF',alignItems:'center',justifyContent:'center',marginTop:11},secondaryText:{fontSize:13,fontWeight:'800',color:C.forest},
 titleBlock:{marginBottom:22},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.5,color:C.coral,marginBottom:4},title:{fontSize:28,fontWeight:'900',letterSpacing:-.7,color:C.ink},subtitle:{fontSize:12,lineHeight:19,color:C.muted,marginTop:8},field:{marginBottom:11},fieldLabel:{fontSize:10,fontWeight:'700',color:C.muted,marginLeft:3,marginBottom:5},fieldInput:{height:50,borderRadius:15,backgroundColor:C.cream,paddingHorizontal:15,fontSize:13,color:C.ink},sectionLabel:{fontSize:10,fontWeight:'900',letterSpacing:1.3,color:C.muted,marginTop:24,marginBottom:11},choices:{flexDirection:'row',gap:7,marginBottom:13},choice:{flex:1,minHeight:44,borderWidth:1,borderColor:'#D8DDD6',borderRadius:14,alignItems:'center',justifyContent:'center',gap:5},choiceOn:{backgroundColor:C.sage,borderColor:C.forest},choiceText:{fontSize:10,fontWeight:'700',color:C.muted},choiceTextOn:{color:C.ink},radio:{width:12,height:12,borderRadius:6,borderWidth:1.5,borderColor:'#A5AFA8'},radioOn:{borderWidth:4,borderColor:C.forest,backgroundColor:'#fff'},
 document:{height:68,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#DDE2DB',flexDirection:'row',alignItems:'center',gap:12},docIcon:{width:42,height:42,borderRadius:14,backgroundColor:C.cream,alignItems:'center',justifyContent:'center'},chevron:{fontSize:26,color:C.muted},notice:{padding:16,borderRadius:18,backgroundColor:C.cream,marginTop:20},noticeTitle:{fontSize:12,fontWeight:'800',color:C.ink},noticeText:{fontSize:11,lineHeight:17,color:C.muted,marginTop:4},center:{alignItems:'center',paddingVertical:28},reviewIcon:{width:74,height:74,borderRadius:37,backgroundColor:C.sage,alignItems:'center',justifyContent:'center'},bigIcon:{fontSize:34,color:C.forest},centerTitle:{fontSize:27,fontWeight:'900',color:C.ink,marginTop:18},centerText:{fontSize:13,lineHeight:20,color:C.muted,textAlign:'center',maxWidth:310,marginTop:8},status:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:C.coral,backgroundColor:'#F5DED7',borderRadius:14,paddingHorizontal:12,paddingVertical:7,marginTop:18},progress:{minHeight:58,flexDirection:'row'},progressCol:{width:38,alignItems:'center'},progressDot:{width:20,height:20,borderRadius:10,borderWidth:2,borderColor:'#B8C1BA',alignItems:'center',justifyContent:'center'},progressDotOn:{borderColor:C.forest,backgroundColor:C.forest},dotCheck:{fontSize:10,fontWeight:'900',color:'#fff'},progressLine:{width:2,flex:1,backgroundColor:'#D7DDD8'},progressLineOn:{backgroundColor:C.forest},progressLabel:{fontSize:13,fontWeight:'700',color:C.muted,paddingTop:2},
 dashHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},dashTitle:{fontSize:30,fontWeight:'900',color:C.ink},verified:{backgroundColor:C.sage,paddingHorizontal:10,paddingVertical:7,borderRadius:14},verifiedText:{fontSize:9,fontWeight:'900',color:C.forest},onlineCard:{borderRadius:24,padding:20,backgroundColor:C.cream,marginTop:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},onlineCardOn:{backgroundColor:C.forest},onlineLabel:{fontSize:9,fontWeight:'900',letterSpacing:1.2,color:C.muted},onlineLabelOn:{color:C.gold},onlineTitle:{fontSize:19,fontWeight:'900',color:C.ink,marginTop:4},onlineTitleOn:{color:'#fff'},onlineText:{fontSize:10,lineHeight:15,color:C.muted,marginTop:4,maxWidth:255},onlineTextOn:{color:'rgba(255,255,255,.65)'},switch:{width:48,height:28,borderRadius:14,backgroundColor:'#C8CEC9',padding:3,justifyContent:'center'},switchOn:{backgroundColor:C.gold},knob:{width:22,height:22,borderRadius:11,backgroundColor:'#fff'},knobOn:{alignSelf:'flex-end'},offerPeek:{marginTop:14,padding:16,borderRadius:19,backgroundColor:C.gold,flexDirection:'row',alignItems:'center',gap:12},pulse:{width:12,height:12,borderRadius:6,backgroundColor:C.coral},offerPeekTitle:{fontSize:13,fontWeight:'900',color:C.ink},offerPeekText:{fontSize:10,color:C.ink,marginTop:3},waiting:{alignItems:'center',paddingVertical:32},waitingEmoji:{fontSize:37},waitingTitle:{fontSize:16,fontWeight:'800',color:C.ink,marginTop:10},waitingText:{fontSize:11,lineHeight:17,color:C.muted,textAlign:'center',maxWidth:255,marginTop:4},metrics:{flexDirection:'row',gap:8},metric:{flex:1,padding:14,borderRadius:17,backgroundColor:C.cream,alignItems:'center'},metricValue:{fontSize:18,fontWeight:'900',color:C.ink},metricLabel:{fontSize:9,color:C.muted,marginTop:3},tip:{padding:15,borderRadius:18,backgroundColor:'#F5E5D9',flexDirection:'row',alignItems:'center',gap:12,marginTop:22},tipIcon:{fontSize:20},
 timer:{alignSelf:'center',paddingHorizontal:13,paddingVertical:7,borderRadius:15,backgroundColor:'#F5DED7'},timerText:{fontSize:9,fontWeight:'800',color:C.coral},earnHero:{alignItems:'center',paddingVertical:27},earnLabel:{fontSize:9,fontWeight:'900',letterSpacing:1.4,color:C.muted},earnValue:{fontSize:48,fontWeight:'900',color:C.ink,letterSpacing:-1.5},earnSub:{fontSize:11,color:C.muted},routeCard:{padding:18,borderRadius:22,backgroundColor:C.cream},routePoint:{flexDirection:'row',alignItems:'center',gap:12},routeIcon:{width:34,height:34,borderRadius:17,backgroundColor:C.forest,alignItems:'center',justifyContent:'center'},routeIconText:{fontSize:11,fontWeight:'900',color:'#fff'},routeLine:{height:24,width:2,backgroundColor:'#AEB9B1',marginLeft:16},offerFacts:{flexDirection:'row',gap:7,marginTop:12},fact:{flex:1,padding:11,borderRadius:15,borderWidth:1,borderColor:'#DCE1DD',alignItems:'center'},factValue:{fontSize:12,fontWeight:'900',color:C.ink},factLabel:{fontSize:8,color:C.muted,textAlign:'center',marginTop:3},actions:{flexDirection:'row',gap:10,marginTop:20},decline:{flex:1,height:54,borderRadius:27,borderWidth:1,borderColor:'#BCC7BF',alignItems:'center',justifyContent:'center'},declineText:{fontSize:13,fontWeight:'800',color:C.ink},accept:{flex:1.5,height:54,borderRadius:27,backgroundColor:C.forest,alignItems:'center',justifyContent:'center'},
 stage:{flexDirection:'row',alignItems:'center',gap:14,marginBottom:18},stageIcon:{width:54,height:54,borderRadius:18,backgroundColor:C.forest,alignItems:'center',justifyContent:'center'},stageIconText:{color:'#fff',fontSize:18,fontWeight:'900'},stageTitle:{fontSize:20,fontWeight:'900',color:C.ink},map:{height:190,borderRadius:24,backgroundColor:'#DCE7DB',alignItems:'center',justifyContent:'center',overflow:'hidden'},mapText:{fontSize:9,letterSpacing:1.1,color:'#76847B',transform:[{rotate:'-10deg'}]},mapMarker:{position:'absolute',left:'36%',top:'42%',width:44,height:44,borderRadius:22,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},code:{alignItems:'center',padding:15,borderRadius:17,backgroundColor:C.cream,marginTop:16},codeLabel:{fontSize:8,fontWeight:'900',letterSpacing:1.2,color:C.muted},codeValue:{fontSize:18,fontWeight:'900',color:C.ink,marginTop:3},checkRow:{minHeight:50,flexDirection:'row',alignItems:'center',gap:11},checkbox:{width:22,height:22,borderRadius:7,borderWidth:1.5,borderColor:'#A4AEA7',alignItems:'center',justifyContent:'center'},checkboxOn:{backgroundColor:C.forest,borderColor:C.forest},checkText:{fontSize:12,color:C.ink},contact:{paddingVertical:17,flexDirection:'row',alignItems:'center',gap:12},avatar:{width:46,height:46,borderRadius:23,backgroundColor:C.gold,alignItems:'center',justifyContent:'center'},avatarText:{fontWeight:'900',color:C.ink},call:{width:42,height:42,borderRadius:21,backgroundColor:C.forest,alignItems:'center',justifyContent:'center'},callText:{fontSize:20,color:'#fff'},
 proofTabs:{flexDirection:'row',backgroundColor:C.cream,borderRadius:18,padding:4},proofTab:{flex:1,height:42,borderRadius:14,alignItems:'center',justifyContent:'center'},proofTabOn:{backgroundColor:C.forest},proofTabText:{fontSize:12,fontWeight:'800',color:C.muted},proofTabTextOn:{color:'#fff'},otp:{alignItems:'center',paddingVertical:25},otpTitle:{fontSize:17,fontWeight:'900',color:C.ink},otpText:{fontSize:11,color:C.muted,textAlign:'center',marginTop:5},otpBoxes:{flexDirection:'row',gap:6,marginTop:20},otpBox:{width:42,height:54,borderRadius:14,backgroundColor:C.cream,textAlign:'center',fontSize:21,fontWeight:'900',color:C.ink},photo:{height:190,borderRadius:22,borderWidth:1.5,borderStyle:'dashed',borderColor:'#ABB6AE',alignItems:'center',justifyContent:'center',marginVertical:22},photoIcon:{fontSize:36,color:C.forest},photoTitle:{fontSize:14,fontWeight:'800',color:C.ink},photoText:{fontSize:10,color:C.muted,marginTop:4},success:{width:76,height:76,borderRadius:38,backgroundColor:C.sage,alignItems:'center',justifyContent:'center'},successText:{fontSize:35,fontWeight:'900',color:C.forest},credit:{padding:22,borderRadius:22,backgroundColor:C.forest,alignItems:'center'},creditLabel:{fontSize:9,fontWeight:'900',letterSpacing:1.3,color:C.gold},creditValue:{fontSize:40,fontWeight:'900',color:'#fff'},creditText:{fontSize:10,color:'rgba(255,255,255,.65)'},
 balance:{padding:22,borderRadius:24,backgroundColor:C.forest,marginBottom:14},balanceLabel:{fontSize:9,fontWeight:'900',letterSpacing:1.3,color:C.gold},balanceValue:{fontSize:40,fontWeight:'900',color:'#fff'},payout:{alignSelf:'flex-start',paddingHorizontal:15,paddingVertical:10,borderRadius:18,backgroundColor:'#fff',marginTop:13},payoutText:{fontSize:11,fontWeight:'900',color:C.forest},moneyRow:{minHeight:66,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#DDE2DB',flexDirection:'row',alignItems:'center',justifyContent:'space-between'},money:{fontSize:15,fontWeight:'900',color:C.forest},deliveryRow:{minHeight:68,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#DDE2DB',flexDirection:'row',alignItems:'center',gap:12},deliveryCheck:{width:38,height:38,borderRadius:14,backgroundColor:C.sage,alignItems:'center',justifyContent:'center'},profile:{padding:17,borderRadius:20,backgroundColor:C.cream,flexDirection:'row',alignItems:'center',gap:13,marginBottom:14},profileAvatar:{width:52,height:52,borderRadius:26,backgroundColor:C.forest,alignItems:'center',justifyContent:'center'},profileAvatarText:{color:'#fff',fontWeight:'900'},exit:{height:45,alignItems:'center',justifyContent:'center',marginTop:25},exitText:{fontSize:11,fontWeight:'700',color:C.muted},
 tabs:{position:'absolute',left:0,right:0,bottom:0,height:84,paddingBottom:14,paddingTop:8,flexDirection:'row',backgroundColor:'rgba(255,253,248,.98)',borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:'#DDE2DB'},tab:{flex:1,alignItems:'center',justifyContent:'center'},tabIcon:{fontSize:19,color:'#8D9690'},tabOn:{color:C.forest,fontWeight:'900'},tabText:{fontSize:9,fontWeight:'600',color:'#8D9690',marginTop:4},tabTextOn:{color:C.forest,fontWeight:'900'},
});
