import { useEffect,useState } from 'react';
import { ActivityIndicator,Alert,KeyboardAvoidingView,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import type { Session } from '@supabase/supabase-js';
import { mobileApi } from './mobileApi';
import { supabase,supabaseConfigured } from './supabase';

const C={ink:'#17372D',forest:'#235643',cream:'#F7F3E9',paper:'#FFFDF8',gold:'#E7A83E',coral:'#D96B4A',sage:'#DDE7D7',muted:'#6E7B74'};
type Tab='Home'|'Orders'|'Scan'|'Issues'|'Me';
type StaffData={me:{fullName:string|null;email:string|null;staffNumber:string;jobTitle:string|null;status:string;joinedAt:string};summary:{ordersWaiting:number;beingPacked:number;onTheWay:number;lowOrOut:number};orders:Array<{id:string;orderNumber:string;status:string;deliverySuburb:string;itemCount:number;placedAt:string|null}>;products:Array<{id:string;name:string;sku:string;available:number;availability:string}>};

export function StaffFlow({close}:{close:()=>void}){
 const [session,setSession]=useState<Session|null>(null),[data,setData]=useState<StaffData|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[fullName,setFullName]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[create,setCreate]=useState(false),[tab,setTab]=useState<Tab>('Home');
 const load=async(s:Session)=>{setLoading(true);setError('');try{setData(await mobileApi<StaffData>('/api/mobile/staff',s.access_token))}catch(e){setError((e as Error).message);setData(null)}finally{setLoading(false)}};
 useEffect(()=>{if(!supabase)return;void supabase.auth.getSession().then(({data:{session:s}})=>{setSession(s);if(s)void load(s)});},[]);
 const submit=async()=>{if(!supabase)return;setLoading(true);setError('');if(create){const {error:e}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{full_name:fullName.trim()}}});setLoading(false);if(e)setError(e.message);else Alert.alert('Account created','An admin must add this account to the staff list before staff tools open.');return}const {data:a,error:e}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(e||!a.session){setError(e?.message??'Could not sign in.');setLoading(false);return}setSession(a.session);await load(a.session)};
 const preview=()=>setData({me:{fullName:null,email:null,staffNumber:'STAFF PREVIEW',jobTitle:'Shop staff',status:'PREVIEW',joinedAt:new Date().toISOString()},summary:{ordersWaiting:0,beingPacked:0,onTheWay:0,lowOrOut:0},orders:[],products:[]});
 if(!data)return <SafeAreaView style={s.login}><StatusBar style="light"/><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={s.fill}><ScrollView contentContainerStyle={s.loginContent}><Pressable onPress={close}><Text style={s.back}>‹</Text></Pressable><Text style={s.kicker}>MUROORA STAFF</Text><Text style={s.loginTitle}>{create?'Create your account':'Staff sign in'}</Text><Text style={s.loginText}>{create?'Create a personal account. An admin will activate staff access—public users cannot choose a staff role.':'Use your individual staff account. There are no shared logins.'}</Text>{create&&<TextInput value={fullName} onChangeText={setFullName} placeholder="Full name" placeholderTextColor="#89958F" style={s.input}/>}<TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="Email" placeholderTextColor="#89958F" style={s.input}/><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Password" placeholderTextColor="#89958F" style={s.input}/>{error?<Text style={s.error}>{error}</Text>:null}<Pressable disabled={loading||!supabaseConfigured} onPress={()=>void submit()} style={s.primary}>{loading?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>{create?'Create account':'Sign in'}</Text>}</Pressable><Pressable onPress={()=>{setCreate(!create);setError('')}} style={s.link}><Text style={s.linkText}>{create?'Already have an account? Sign in':'New employee? Create an account'}</Text></Pressable>{__DEV__&&<Pressable onPress={preview} style={s.preview}><Text style={s.previewText}>Preview staff interface</Text></Pressable>}</ScrollView></KeyboardAvoidingView></SafeAreaView>;
 const content=tab==='Home'?<><Title small="ACTION REQUIRED" big={`Hello${data.me.fullName?`, ${data.me.fullName.split(' ')[0]}`:''}`}/><View style={s.metrics}><Metric n={data.summary.ordersWaiting} label="New orders"/><Metric n={data.summary.beingPacked} label="Picking"/><Metric n={data.summary.onTheWay} label="On the way"/><Metric n={data.summary.lowOrOut} label="Stock issues"/></View><Queue orders={data.orders.filter(o=>!['DELIVERED','CANCELLED'].includes(o.status)).slice(0,5)}/></>:tab==='Orders'?<><Title small="WORK QUEUE" big="Orders"/><Queue orders={data.orders}/></>:tab==='Scan'?<><Title small="PRODUCT LOOKUP" big="Scan"/><Empty text="Barcode scanning is prepared for a later phase. Use product search in stock for now."/></>:tab==='Issues'?<><Title small="REPORT A PROBLEM" big="Issues"/><Empty text="Choose an active order or product first so every issue is recorded against the right item."/></>:<><Title small={data.me.staffNumber} big={data.me.fullName??'Staff profile'}/><View style={s.card}><Text style={s.cardTitle}>{data.me.jobTitle??'Shop staff'}</Text><Text style={s.meta}>{data.me.status} · joined {new Date(data.me.joinedAt).toLocaleDateString()}</Text><Text style={s.meta}>{data.me.email}</Text></View><Pressable onPress={()=>void supabase?.auth.signOut().then(()=>{setSession(null);setData(null)})} style={s.link}><Text style={s.linkText}>Sign out</Text></Pressable></>;
 return <SafeAreaView style={s.safe}><StatusBar style="dark"/><View style={s.phone}><View style={s.top}><Pressable onPress={close}><Text style={s.topBack}>‹</Text></Pressable><Text style={s.topTitle}>Muroora Staff</Text><Text style={s.staffId}>{data.me.staffNumber}</Text></View><ScrollView contentContainerStyle={s.content}>{content}</ScrollView><View style={s.tabs}>{(['Home','Orders','Scan','Issues','Me'] as Tab[]).map(x=><Pressable key={x} onPress={()=>setTab(x)} style={s.tab}><Text style={[s.tabText,tab===x&&s.tabOn]}>{x}</Text></Pressable>)}</View></View></SafeAreaView>;
}
function Title({small,big}:{small:string;big:string}){return <View><Text style={s.eyebrow}>{small}</Text><Text style={s.title}>{big}</Text></View>};
function Metric({n,label}:{n:number;label:string}){return <View style={s.metric}><Text style={s.metricN}>{n}</Text><Text style={s.meta}>{label}</Text></View>};
function Queue({orders}:{orders:StaffData['orders']}){return <View style={s.queue}>{orders.length?orders.map(o=><View key={o.id} style={s.order}><View style={s.grow}><Text style={s.cardTitle}>{o.orderNumber}</Text><Text style={s.meta}>{o.itemCount} items · {o.deliverySuburb}</Text></View><Text style={s.pill}>{o.status.replaceAll('_',' ')}</Text></View>):<Empty text="No orders need attention."/>}</View>};
function Empty({text}:{text:string}){return <View style={s.empty}><Text style={s.meta}>{text}</Text></View>};
const s=StyleSheet.create({fill:{flex:1},login:{flex:1,backgroundColor:C.forest},loginContent:{padding:26,paddingTop:45},back:{fontSize:40,color:'#fff'},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.5,color:C.gold,marginTop:35},loginTitle:{fontSize:36,fontWeight:'900',color:'#fff',marginTop:5},loginText:{fontSize:13,lineHeight:20,color:'rgba(255,255,255,.7)',marginVertical:18},input:{height:52,borderRadius:16,backgroundColor:'rgba(255,255,255,.12)',paddingHorizontal:15,color:'#fff',marginBottom:10},error:{color:'#FFD1C2',fontSize:11},primary:{height:54,borderRadius:27,backgroundColor:C.coral,alignItems:'center',justifyContent:'center',marginTop:12},primaryText:{color:'#fff',fontWeight:'900'},link:{padding:18,alignItems:'center'},linkText:{color:C.gold,fontWeight:'800',fontSize:12},preview:{height:50,borderRadius:25,borderWidth:1,borderColor:'rgba(255,255,255,.35)',alignItems:'center',justifyContent:'center'},previewText:{color:'#fff',fontSize:11,fontWeight:'800'},safe:{flex:1,backgroundColor:C.paper},phone:{flex:1,maxWidth:440,width:'100%',alignSelf:'center',backgroundColor:C.paper},top:{height:72,paddingHorizontal:18,backgroundColor:C.forest,flexDirection:'row',alignItems:'center',gap:12},topBack:{fontSize:34,color:'#fff'},topTitle:{flex:1,fontSize:18,fontWeight:'900',color:'#fff'},staffId:{fontSize:9,color:C.gold,fontWeight:'800'},content:{padding:20,paddingBottom:110},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.4,color:C.coral},title:{fontSize:30,fontWeight:'900',color:C.ink,marginTop:4,marginBottom:18},metrics:{flexDirection:'row',flexWrap:'wrap'},metric:{width:'50%',borderWidth:4,borderColor:C.paper,backgroundColor:C.cream,borderRadius:20,padding:17},metricN:{fontSize:30,fontWeight:'900',color:C.ink},meta:{fontSize:10,lineHeight:16,color:C.muted,marginTop:3},queue:{marginTop:18},order:{minHeight:76,borderBottomWidth:1,borderBottomColor:'#DDE2DB',flexDirection:'row',alignItems:'center',gap:10},grow:{flex:1},card:{padding:18,borderRadius:20,backgroundColor:C.cream},cardTitle:{fontSize:13,fontWeight:'900',color:C.ink},pill:{fontSize:7,fontWeight:'900',color:C.forest,backgroundColor:C.sage,padding:7,borderRadius:10,overflow:'hidden'},empty:{padding:22,borderRadius:18,backgroundColor:C.cream,alignItems:'center'},tabs:{position:'absolute',bottom:0,left:0,right:0,height:82,backgroundColor:C.paper,borderTopWidth:1,borderTopColor:'#DDE2DB',flexDirection:'row'},tab:{flex:1,alignItems:'center',justifyContent:'center'},tabText:{fontSize:9,color:C.muted,fontWeight:'700'},tabOn:{color:C.forest,fontWeight:'900'}});
