'use client'

import Link from 'next/link'
import { useMemo,useState } from 'react'

type Kind='All'|'Shopping'|'Food'|'Accommodation'|'Services'|'Education'
const rows: ReadonlyArray<{kind:Kind;icon:string;title:string;business:string;area:string;price:string;mode:'Commerce'|'Enquiry'}>=[
 {kind:'Shopping',icon:'🛍️',title:'Muroora Mart pantry preview',business:'Muroora Mart · Founding Merchant',area:'Mutare Central',price:'$5.00',mode:'Commerce'},
] as const

export function MarketplacePreview(){
 const [kind,setKind]=useState<Kind>('All'),[query,setQuery]=useState(''),[selected,setSelected]=useState<(typeof rows)[number]|null>(null),[view,setView]=useState<'discover'|'portal'|'chat'>('discover'),[contact,setContact]=useState(false)
 const found=useMemo(()=>rows.filter(x=>(kind==='All'||x.kind===kind)&&`${x.title} ${x.business} ${x.area}`.toLowerCase().includes(query.toLowerCase())),[kind,query])
 /* The business application is REAL and lives at /marketplace/apply. It used
    to be a mock here whose submit button raised alert('Preview only'), which
    is what somebody hits when they try to list their business. */
 if(view==='portal')return <PreviewShell back={()=>setView('discover')} eyebrow="Merchant portal preview" title="What needs attention?"><div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[['0','New orders'],['0','Enquiries'],['0','Messages'],['80%','Profile complete']].map(([n,l])=><div key={l} className="rounded-3xl bg-paper-sunk p-6"><p className="text-h2 font-extrabold">{n}</p><p className="mt-2 text-small text-ink-soft">{l}</p></div>)}</div><div className="mt-10 divide-y divide-rule border-y border-rule">{['Listings / products / menu','Orders & enquiries','Messages','Availability','Performance','Business profile','Settings'].map(x=><button key={x} className="flex min-h-16 w-full items-center justify-between text-left font-bold" onClick={()=>alert('Preview only - shared backend required.')}>{x}<span>›</span></button>)}</div></PreviewShell>
 if(view==='chat'&&selected)return <PreviewShell back={()=>setView('discover')} eyebrow={selected.business} title="Musuwo Chat"><Notice title="Contact details stay private">Phone and WhatsApp details remain hidden until an authorized, audited contact release.</Notice><div className="mt-6 min-h-52 rounded-3xl bg-paper-sunk p-8 text-center text-ink-soft">No preview messages. Ask about availability, pricing or a viewing.</div><input className="mt-4 min-h-14 w-full rounded-2xl bg-paper-sunk px-5" placeholder="Write a message"/><div className="mt-4 flex flex-wrap gap-3"><button className="rounded-full bg-support px-6 py-3 font-bold text-white" onClick={()=>alert('Message backend required.')}>Send message</button><button className="rounded-full border border-support px-6 py-3 font-bold text-support" onClick={()=>setContact(true)}>{contact?'Contact requested':'Request contact details'}</button></div>{contact&&<Notice title="Request recorded">Production release occurs only after server authorization and an audit event.</Notice>}</PreviewShell>
 if(selected)return <PreviewShell back={()=>setSelected(null)} eyebrow={`${selected.kind} · ${selected.business}`} title={selected.title}><div className="grid gap-8 lg:grid-cols-[1fr_.7fr]"><div className="flex min-h-72 items-center justify-center rounded-[2rem] bg-paper-sunk text-[7rem]">{selected.icon}</div><div><span className="chip chip-live">Preview listing</span><p className="mt-6 text-h2 font-extrabold text-support">{selected.price}</p><p className="mt-4 text-ink-soft">{selected.area}. This page demonstrates a typed {selected.mode.toLowerCase()} listing and clear business attribution.</p>{selected.kind==='Accommodation'&&<Notice title="Accommodation safety">Do not send deposits solely because someone claims to represent a property. Verify the property and agreement first.</Notice>}<button className="mt-7 rounded-full bg-support px-7 py-4 font-bold text-white" onClick={()=>selected.mode==='Enquiry'?setView('chat'):alert('This would use one merchant per checkout initially.')}>{selected.mode==='Enquiry'?'Chat with business':'Add to basket'}</button><button className="ml-3 mt-3 rounded-full border border-rule px-6 py-3 font-bold" onClick={()=>alert('A report creates a review case; it does not imply guilt.')}>Report</button></div></div></PreviewShell>
 return <main><section className="bg-support px-gutter py-20 text-white"><div className="mx-auto max-w-[86rem]"><p className="font-mono text-micro uppercase tracking-label text-accent">Musuwo Marketplace · preview</p><h1 className="mt-4 max-w-[15ch] text-mega leading-[.95]">Find trusted local options.</h1><p className="mt-6 max-w-2xl text-lead text-white/75">Shop, order food, find accommodation, or enquire with a local service - all through the right interaction flow.</p></div></section><section className="mx-auto max-w-[86rem] px-gutter py-12"><input value={query} onChange={e=>setQuery(e.target.value)} className="min-h-16 w-full rounded-3xl bg-paper-sunk px-6 text-lead" placeholder="Search shops, food, rooms, tutors and services…"/><div className="mt-5 flex flex-wrap gap-2">{(['All','Shopping','Food','Accommodation','Services','Education'] as Kind[]).map(x=><button key={x} onClick={()=>setKind(x)} className={`chip ${kind===x?'border-support bg-support text-white':''}`}>{x}</button>)}</div><div className="mt-8 grid gap-4 md:grid-cols-2"><Link href="/marketplace/apply" className="rounded-3xl bg-accent p-7 text-left text-white"><span className="font-mono text-micro uppercase tracking-label">Sell or list</span><strong className="mt-2 block text-h3">Musuwo for Business →</strong></Link><button className="rounded-3xl bg-paper-sunk p-7 text-left" onClick={()=>setView('portal')}><span className="font-mono text-micro uppercase tracking-label text-ink-faint">Approved businesses</span><strong className="mt-2 block text-h3">Merchant portal preview →</strong></button></div><h2 className="mt-14 text-h2">Discover Mutare</h2><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{found.map(x=><button key={x.title} onClick={()=>setSelected(x)} className="rounded-3xl border border-rule p-5 text-left transition hover:border-support"><div className="flex min-h-44 items-center justify-center rounded-2xl bg-paper-sunk text-6xl">{x.icon}</div><div className="mt-5 flex justify-between gap-3"><h3 className="font-bold">{x.title}</h3><span className="chip h-fit">{x.mode}</span></div><p className="mt-2 text-small text-ink-soft">{x.business} · {x.area}</p><p className="mt-4 font-bold text-support">{x.price}</p></button>)}</div></section></main>
}
function PreviewShell({back,eyebrow,title,children}:{back:()=>void;eyebrow:string;title:string;children:React.ReactNode}){return <main className="mx-auto max-w-[86rem] px-gutter py-12"><button onClick={back} className="font-mono text-micro uppercase tracking-label text-support">← Marketplace</button><p className="mt-10 font-mono text-micro uppercase tracking-label text-accent">{eyebrow}</p><h1 className="mt-3 text-mega leading-none">{title}</h1><div className="mt-10">{children}</div></main>}
/* The Field helper went with the mock application form. The real one is a
   server action at /marketplace/apply with its own inputs. */
function Notice({title,children}:{title:string;children:React.ReactNode}){return <div className="mt-6 rounded-2xl bg-accent-wash p-5"><strong>{title}</strong><p className="mt-2 text-small text-ink-soft">{children}</p></div>}


