import { relations } from 'drizzle-orm'
import {
  bigint,
  index,
  integer,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core'

import { currencyEnum, id, metadata, storeId, timestamps } from './_shared'
import { products, stores } from './catalogue'
import { users } from './identity'

/**
 * Orders, their line items, and the event log that is their real history.
 */

/**
 * Every internal state, exactly as the brief lists them.
 *
 * The brief also says: "Do not force every status into the customer UI."
 * `customerFacingStatus()` in lib/orders.ts collapses these to the six a
 * customer should see. A customer does not need to know the difference between
 * PACKED and READY_FOR_PICKUP; the shop does.
 */
export const orderStatusEnum = pgEnum('order_status', [
  'DRAFT',
  'PENDING_PAYMENT',
  'PAYMENT_CONFIRMED',
  'ORDER_RECEIVED',
  'ACCEPTED',
  'PICKING',
  'AWAITING_SUBSTITUTION_APPROVAL',
  'PACKED',
  'READY_FOR_PICKUP',
  'DRIVER_ASSIGNED',
  'RIDER_AT_STORE',
  'COLLECTED',
  'OUT_FOR_DELIVERY',
  'RIDER_ARRIVED',
  'DELIVERED',
  'DELIVERY_FAILED',
  'CANCELLED',
  'REFUNDED',
  'PARTIALLY_REFUNDED',
])

/** What the customer chose to happen if something is out of stock. */
export const substitutionPreferenceEnum = pgEnum('substitution_preference', [
  'NONE',
  'SIMILAR',
  'CONTACT_ME',
])

export const orders = pgTable(
  'orders',
  {
    id: id(),
    storeId: storeId().references(() => stores.id),

    /**
     * Human-facing identifier: MM-000001.
     *
     * The brief: "Do not expose raw sequential database IDs if avoidable."
     * The UUID above is the true key; this is what goes on a WhatsApp message
     * and what someone reads down a phone line. Generated by a Postgres
     * sequence in the migration, so two simultaneous checkouts cannot collide.
     */
    orderNumber: text('order_number').notNull().unique(),

    /* ---- BUYER: who paid. May be abroad. ------------------------------- */
    buyerId: uuid('buyer_id').references(() => users.id),
    buyerName: text('buyer_name').notNull(),
    buyerEmail: text('buyer_email'),
    buyerPhone: text('buyer_phone'),
    /** Where the buyer is. The diaspora case is the whole point. */
    buyerCountryCode: text('buyer_country_code'),

    /* ---- RECIPIENT: who receives. Often a different person entirely. ----
       Denormalised onto the order rather than joined to saved_recipients,
       deliberately. If someone edits a saved recipient's address next month,
       the record of where THIS order actually went must not change with it. */
    recipientName: text('recipient_name').notNull(),
    recipientPhone: text('recipient_phone').notNull(),
    recipientRelationship: text('recipient_relationship'),
    deliveryLine1: text('delivery_line1').notNull(),
    deliveryLine2: text('delivery_line2'),
    deliverySuburb: text('delivery_suburb').notNull(),
    deliveryCity: text('delivery_city').notNull().default('Mutare'),
    deliveryDirections: text('delivery_directions'),
    deliveryLatitude: text('delivery_latitude'),
    deliveryLongitude: text('delivery_longitude'),
    alternativeContactName: text('alternative_contact_name'),
    alternativeContactPhone: text('alternative_contact_phone'),

    /* ---- Money. All minor units, one currency for the whole order. ------ */
    currency: currencyEnum('currency').notNull().default('USD'),
    subtotalAmount: bigint('subtotal_amount', { mode: 'bigint' }).notNull(),
    deliveryFeeAmount: bigint('delivery_fee_amount', { mode: 'bigint' })
      .notNull()
      .default(0n),
    discountAmount: bigint('discount_amount', { mode: 'bigint' })
      .notNull()
      .default(0n),
    totalAmount: bigint('total_amount', { mode: 'bigint' }).notNull(),

    /**
     * The USD rate in force WHEN THIS ORDER WAS PLACED.
     *
     * Not looked up at read time. Zimbabwe runs USD and ZWL in parallel at a
     * moving rate, so a ZWL order reconciled in six months against today's
     * rate would be simply wrong. Captured here at the moment of sale — see
     * D-003. Null when the order is already in USD.
     */
    fxRateToUsd: text('fx_rate_to_usd'),

    status: orderStatusEnum('status').notNull().default('DRAFT'),
    substitutionPreference: substitutionPreferenceEnum('substitution_preference')
      .notNull()
      .default('CONTACT_ME'),
    customerNote: text('customer_note'),

    zoneId: uuid('zone_id'),
    placedAt: timestamp('placed_at', { withTimezone: true }),
    ...timestamps(),
  },
  (t) => [
    index('orders_store_status_idx').on(t.storeId, t.status),
    index('orders_buyer_idx').on(t.buyerId),
    index('orders_placed_idx').on(t.placedAt),
    index('orders_recipient_phone_idx').on(t.recipientPhone),
  ],
)

/**
 * Line items.
 *
 * Name and price are COPIED onto the row, not read through the product join.
 * If the shop raises the price of cooking oil next week, this order must still
 * show what the customer was actually charged. A join would silently rewrite
 * history every time a price changed.
 */
export const orderItems = pgTable(
  'order_items',
  {
    id: id(),
    orderId: uuid('order_id')
      .notNull()
      .references(() => orders.id, { onDelete: 'cascade' }),
    productId: uuid('product_id').references(() => products.id),

    /** As it was at the time of sale. */
    productName: text('product_name').notNull(),
    productSku: text('product_sku'),
    unitSize: text('unit_size'),

    quantity: integer('quantity').notNull(),
    unitPriceAmount: bigint('unit_price_amount', { mode: 'bigint' }).notNull(),
    lineTotalAmount: bigint('line_total_amount', { mode: 'bigint' }).notNull(),

    /** Set once packing happens. */
    quantityPicked: integer('quantity_picked'),
    /** Points at the product actually supplied instead. */
    substitutedWithProductId: uuid('substituted_with_product_id').references(
      () => products.id,
    ),
    substitutionNote: text('substitution_note'),

    ...timestamps(),
  },
  (t) => [index('order_items_order_idx').on(t.orderId)],
)

/**
 * The event log. APPEND-ONLY — see D-004.
 *
 * `orders.status` is a cached projection of this table, not the source of
 * truth. The brief's "Never silently modify order states" is only enforceable
 * if every change leaves a row here saying who did it and what it was before.
 */
export const orderEvents = pgTable(
  'order_events',
  {
    id: id(),
    orderId: uuid('order_id')
      .notNull()
      .references(() => orders.id, { onDelete: 'cascade' }),

    eventType: text('event_type').notNull(),
    previousStatus: orderStatusEnum('previous_status'),
    newStatus: orderStatusEnum('new_status'),

    /** CUSTOMER, STAFF, ADMIN, RIDER, SYSTEM. Text so 'SYSTEM' needs no user. */
    actorType: text('actor_type').notNull(),
    actorId: uuid('actor_id').references(() => users.id),

    metadata: metadata(),

    createdAt: timestamp('created_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [index('order_events_order_idx').on(t.orderId, t.createdAt)],
)

export const ordersRelations = relations(orders, ({ one, many }) => ({
  store: one(stores, { fields: [orders.storeId], references: [stores.id] }),
  buyer: one(users, { fields: [orders.buyerId], references: [users.id] }),
  items: many(orderItems),
  events: many(orderEvents),
}))

export const orderItemsRelations = relations(orderItems, ({ one }) => ({
  order: one(orders, { fields: [orderItems.orderId], references: [orders.id] }),
  product: one(products, {
    fields: [orderItems.productId],
    references: [products.id],
  }),
}))

export const orderEventsRelations = relations(orderEvents, ({ one }) => ({
  order: one(orders, { fields: [orderEvents.orderId], references: [orders.id] }),
  actor: one(users, { fields: [orderEvents.actorId], references: [users.id] }),
}))
