import { relations } from 'drizzle-orm'
import {
  index,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core'

import { id, storeId, timestamps } from './_shared'
import { stores } from './catalogue'
import { users } from './identity'

/**
 * Staff profiles.
 *
 * Addendum §8: each employee can later have a photograph, a generated Muroora
 * staff ID, a full name, a role, an account status and a joined date. The
 * brief says not to prioritise printable cards or QR referral systems yet, but
 * to make them possible later - so the fields exist and nothing renders them.
 *
 * SEPARATE FROM `user_roles` ON PURPOSE. `user_roles` answers "may this person
 * edit prices" and is the security boundary. This table answers "who is this
 * person at work" - their staff number, their photograph, whether they are
 * currently employed. Conflating the two would mean a suspended employee
 * either keeps their access or loses their record.
 *
 * The profile does not grant anything. Revoking access is done by removing the
 * role; setting status here to SUSPENDED is the HR fact, and the two are kept
 * in step by the admin screens rather than by a foreign key, because an
 * ex-employee's record must outlive their access.
 */

export const staffStatusEnum = pgEnum('staff_status', [
  'ACTIVE',
  'SUSPENDED',
  'LEFT',
])

export const staffProfiles = pgTable(
  'staff_profiles',
  {
    id: id(),
    storeId: storeId().references(() => stores.id),

    userId: uuid('user_id')
      .notNull()
      .unique()
      .references(() => users.id, { onDelete: 'cascade' }),

    /**
     * MM-STF-0001. Generated by a Postgres sequence in the migration, for the
     * same reason order numbers are: two admins promoting two people at once
     * must not hand out the same number. Never reused, even after someone
     * leaves - a staff number that comes back means two people share a
     * history.
     */
    staffNumber: text('staff_number').notNull().unique(),

    /** What they do, in the shop's words. Not a permission. */
    jobTitle: text('job_title'),

    /**
     * Supabase Storage path, never a public URL. A staff photograph is
     * personal data - it is resolved through a signed URL at render time, the
     * same discipline the rider documents will need in Phase 3.
     */
    photoPath: text('photo_path'),

    status: staffStatusEnum('status').notNull().default('ACTIVE'),

    joinedAt: timestamp('joined_at', { withTimezone: true })
      .notNull()
      .defaultNow(),
    leftAt: timestamp('left_at', { withTimezone: true }),

    /** Who promoted them. Also written to audit_log; kept here for the screen. */
    createdBy: uuid('created_by').references(() => users.id),

    notes: text('notes'),
    ...timestamps(),
  },
  (t) => [
    index('staff_profiles_store_idx').on(t.storeId, t.status),
    index('staff_profiles_user_idx').on(t.userId),
  ],
)

export const staffProfilesRelations = relations(staffProfiles, ({ one }) => ({
  user: one(users, { fields: [staffProfiles.userId], references: [users.id] }),
  store: one(stores, {
    fields: [staffProfiles.storeId],
    references: [stores.id],
  }),
  creator: one(users, {
    fields: [staffProfiles.createdBy],
    references: [users.id],
  }),
}))
